### ISSUE TITLE
Failed Installation

### ISSUE THREAD

**Issue by Brendinho106** [elastic/windows-installers#114] opened 2017-09-27 22:52 UTC
[InstallationLog.LOG](https://github.com/elastic/windows-installers/files/1338931/InstallationLog.LOG)

Installation failed on Win10 PC

**Comment by Brendinho106** [comment] 2017-09-27 22:59
Nevermind, solved it myself. I opted not to install as a service and instead launch manually.

**Comment by russcam** [comment] 2017-09-28 05:35
@Brendinho106 The problem is that there is no `JAVA_HOME` environment variable pointing to a valid version of Java or no Java in the `PATH` environment variable:
```
[0] installing lang-python installing lang-python
Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME 
```

This is needed when installing plugins as a Java CLI tool is invoked in order to perform the installation.

I'm going to close this as the fix is to set `JAVA_HOME` to the directory of a valid Java installation, or include the directory to `java.exe` in the `PATH` environment variable. Hope that helps 👍

**Closed by russcam** 2017-09-28 05:35 UTC
