### ISSUE TITLE
Issues with Installation on Windows 10

### ISSUE THREAD

**Issue by rlgreen91** [elastic/windows-installers#79] opened 2017-08-19 03:56 UTC
Hello all,

I had an issue with installing Elasticsearch on Windows 10 using the MSI.  First, I tried to install Elasticsearch with a couple of plugins, but the installation failed for some reason.  Next, I tried to install Elasticsearch by itself, but the installation still failed.  Finally, I tried to install just Elasticsearch but I didn't select the option to start the service immediately after installation.  That did work. 

Hoping this can provide some clues to people looking to install Elasticsearch as well as the maintainers of the installer.

**Comment by russcam** [comment] 2017-08-19 07:54
@rlgreen91 thank you for opening this. Do you have the MSI log for the failed installation? There is a link to it in the closing view when the install fails.

**Comment by rlgreen91** [comment] 2017-08-20 03:55
@russcam, I know what you're talking about, as I opened it up each time it failed, but I can't find them.  Not even the log from the last installation, which was successful.  I'll keep looking, but if you know where they would be stored, please let me know - they're not in the Program Files folder for Elasticsearch like I expected.

**Comment by russcam** [comment] 2017-08-20 22:17
@rlgreen91 The [default location is in `%TEMP%`, with a name that matches the pattern `MSI<random characters>.log`](https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html#install-msi-command-line). If you order the files by date descending, you should find them there.

**Comment by clickstefan** [comment] 2017-08-21 20:06
Also failed for me. Unsure if related, but I am running windows 10.
Here is the part of the log that looks interesting:
```
[2017-08-21T21:57:12,540][WARN ][o.e.e.NodeEnvironment    ] [ALEX] lock assertion failed
java.nio.file.AccessDeniedException: C:\ProgramData\Elastic\Elasticsearch\data\nodes\0\node.lock
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:193) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[?:1.8.0_144]
	at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:177) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.elasticsearch.env.NodeEnvironment.assertEnvIsLocked(NodeEnvironment.java:941) [elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.env.NodeEnvironment.nodeDataPaths(NodeEnvironment.java:743) [elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.gateway.GatewayMetaState.ensureNoPre019ShardState(GatewayMetaState.java:291) [elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:82) [elasticsearch-5.5.1.jar:5.5.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_144]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) [elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjecto
```

...
```
[2017-08-21T21:57:12,957][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [ALEX] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.IllegalStateException: environment is not locked
  at org.elasticsearch.gateway.GatewayMetaState.<init>(Unknown Source)
```

**Comment by clickstefan** [comment] 2017-08-21 20:09
Seems my problem is related with: https://github.com/elastic/windows-installers/issues/68

**Comment by rlgreen91** [comment] 2017-08-21 20:32
Sorry @russcam, but I can't find them in TEMP.  Tried running a search, but that didn't turn up anything either.

**Comment by clickstefan** [comment] 2017-08-22 15:25
@rlgreen91  could you start elasticsearch, after the successfull install (when you didn't select the option to start the service immediately)? 

The install also finished successfully for me, with that option unchecked, but it just shows that the problem was with starting elasticsearch and not the install procedures. As starting elasticsearch gives the same errors : `lock assertion failed`

**Comment by rlgreen91** [comment] 2017-08-23 03:23
Yes, I was able to install, and then later start the service successfully.

**Comment by russcam** [comment] 2017-08-23 04:38
> Sorry @russcam, but I can't find them in TEMP. Tried running a search, but that didn't turn up anything either.

@rlgreen91 not a problem. you can re-run the installer again and follow the link on the closing view when the installer fails to obtain the log. Based on having been able to run it successfully when unchecking `"start the service after this installation is complete"`, the issue looks to be related to the installer not seeing the service start successfully in the provided time. We're looking into why/how this can happen.

@clickstefan did you run the installation on top of an existing Elasticsearch installation installed with the `.zip`? Or was it a completely fresh install, with no existing Elasticsearch installation?

**Comment by clickstefan** [comment] 2017-08-23 06:52
Wasn't installed previously, but it was my second install attempt, after the first failed and uninstalled, having the run after checkbox.

**Comment by russcam** [comment] 2017-08-23 07:08
Thanks for clarifying. What user did you choose to run the Windows Service as?

**Comment by clickstefan** [comment] 2017-08-23 11:22
@russcam The first & default option: **Local System account**.

**Comment by rlgreen91** [comment] 2017-08-27 19:51
I tried to upgrade my version of Elasticsearch - I forgot to select not to start the service immediately, so it failed. Here are the logs:

**Comment by rlgreen91** [comment] 2017-08-27 19:57
Ah, so I'm running into an issue - it can't attach the files saved in that type and the whole log is too long.  I did find this though:

`DEBUG: Error 2911:  Could not remove the folder C:\Config.Msi\.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2911. The arguments are: C:\Config.Msi\, , `

**Comment by russcam** [comment] 2017-11-15 09:57
@rlgreen91 apologies for not getting back sooner. 

> DEBUG: Error 2911: Could not remove the folder C:\Config.Msi\. The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2911. The arguments are: C:\Config.Msi\, ,

I don't think this is an issue in this case. It can be an artifact of a problem with installation, but not the problem itself, if that makes sense.

**Comment by russcam** [comment] 2017-11-15 10:00
@clickstefan I think your issue is fixed by #131.

The installer creates write access that are propagated to child container objects for `BUILTIN\Users`, but not for both child container objects and child leaf objects, which are needed to write log files and directories and files to data directory when running as a non-elevated user,

This will be in the next release of the installer. In the meantime, it's possible to run the elasticsearch.exe from an elevated command prompt.

**Comment by netcore-jroger** [comment] 2018-02-09 06:29
I have same error.
=====
[2018-02-09T14:11:17,999][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalStateException: Unable to access 'java.io.tmpdir' (${ES_TMPDIR})
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:299) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:262) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:208) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.2.1.jar:6.2.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) [elasticsearch-6.2.1.jar:6.2.1]
Caused by: java.nio.file.AccessDeniedException: `C:\WINDOWS\system32\${ES_TMPDIR}`
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[?:1.8.0_131]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:1.8.0_131]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:1.8.0_131]
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504) ~[?:1.8.0_131]
	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_131]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_131]
	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_131]
	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:421) ~[elasticsearch-6.2.1.jar:6.2.1]
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68) ~[elasticsearch-6.2.1.jar:6.2.1]
	... 12 more

**Comment by russcam** [comment] 2018-02-09 06:31
@netcore-jroger I think this is related to #166. Would you mind following up on that issue with what account you're running with.

**Comment by netcore-jroger** [comment] 2018-02-09 06:33
@russcam let me try.

**Comment by netcore-jroger** [comment] 2018-02-09 06:44
I used Local Account ware work fine. Thanks!

**Closed** 2018-06-20 06:17 UTC
