### ISSUE TITLE
Error occured during installation - Windows 2016 server Elasticsearch 7.7.0 

### ISSUE THREAD

**Issue by amblinalong** [elastic/windows-installers#365] opened 2020-05-14 16:56 UTC
### Environment

no

UT, USA

### Expected Behaviour
Completed and successful installation

### Actual Behaviour
error occurred installation.  installation did not happen.

### Steps to reproduce the behaviour
Windows 2016 Server, logged in as local administrator, installing software on C: drive but installing logs, data, config on D: drive;  Completed MSI installation, installation proceeded and then failed before completion.

fresh install
1.
2.
3.

**Comment by amblinalong** [comment] 2020-05-14 16:57
[MSI70dd7.LOG](https://github.com/elastic/windows-installers/files/4629811/MSI70dd7.LOG)

**Comment by amblinalong** [comment] 2020-05-14 16:58
accidentally closed while providing log file.  original log upload was not successful

**Comment by yommy45** [comment] 2020-05-17 04:24
I am also having the same problem. I tried it so many times with no luck. Is there any other version that can be installed aside 7.7.0?

**Comment by russcam** [comment] 2020-05-20 00:18
Closing this as duplicate of #363. Please see workaround: https://github.com/elastic/windows-installers/issues/363#issuecomment-631158455

**Closed by russcam** 2020-05-20 00:18 UTC
Labels: v7.7.0
