### ISSUE TITLE
[7.11] Expected two arguments specifying path to ES_PATH_CONF and plugins directory

### ISSUE THREAD

**Issue by UkrZilla** [elastic/windows-installers#401] opened 2021-02-11 07:48 UTC
During update 7.10.2 to 7.11 at the end of update service fails with error:

`Service cannot be started. Elastic.ProcessHosts.Process.StartupException: Could not evaluate jvm.options file. result: Exception in thread "main" java.lang.IllegalArgumentException: Expected two arguments specifying path to ES_PATH_CONF and plugins directory, but was [C:\Elasticsearch\Config]
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:72)

   at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess.CreateObservableProcessArguments(IEnumerable`1 args)
   at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess..ctor(IObservableProcess process, IConsoleOutHandler consoleOutHandler, IFileSystem fileSystem, ElasticsearchEnvironmentConfiguration env, JavaConfiguration java, IElasticsearchTool jvmOptionsParser, IElasticsearchTool javaVersionChecker, ManualResetEvent completedHandle, IEnumerable`1 args)
   at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess..ctor(ManualResetEvent completedHandle, IEnumerable`1 args)
   at Elastic.ProcessHosts.Elasticsearch.Serv...`

Fresh install with the same error

**Comment by ygel** [comment] 2021-02-11 15:34
@UkrZilla thank you for reporting this, likely a duplicate of https://github.com/elastic/windows-installers/issues/402

**Closed** 2021-02-11 18:27 UTC
Labels: bug, v7.11.0
