### ISSUE TITLE
Installation failed through MSI

### ISSUE THREAD

**Issue by s-lamani** [elastic/windows-installers#299] opened 2019-05-21 07:48 UTC
### Environment
Windows 10 Pro 64 bit

### Expected Behaviour
![ELK](https://user-images.githubusercontent.com/24887547/58077521-54555700-7bca-11e9-9ab6-eb91663b7440.JPG)

### Steps to reproduce the behaviour

1.Run MSI elasticsearch-7.0.1
2.
3.

[MSIec29.LOG](https://github.com/elastic/windows-installers/files/3201310/MSIec29.LOG)

**Comment by s-lamani** [comment] 2019-06-14 13:12
Hi,
Waiting for reply.

**Comment by ygel** [comment] 2019-07-10 16:16
Duplicate of #305

**Closed by ygel** 2019-07-10 16:16 UTC
