### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yommy45** [elastic/windows-installers#367] opened 2020-05-17 04:26 UTC
I have tried to installed v7.7.0 many times and I keep getting the same error message.

Documentation for the Elasticsearch Windows Installer can be found at

https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html

Be sure to select the documentation version relevant to the installer version you
are using.

### Failed Installations

If you are reporting an issue that occurred during installation, we ask that you
attach the installation log file to your issue to help diagnose the root cause.

When installing using the UI, a link to the log file will be provided at the end of a
failed installation. If you have already closed the UI, the log file can be found in
the %TEMP% directory with a randomly generated name adhering to the format MSI<random>.LOG.
It should be the most recent log file.

When installing from the command-line, the log file can be captured by passing the /l*v <logfilename>
flag as per the documentation: 

https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html#install-msi-command-line

-->

### Steps to reproduce the behaviour

1.
2.
3.

**Comment by yommy45** [comment] 2020-05-17 04:31
Screenshot attached

**Comment by reighnman** [comment] 2020-05-19 14:19
Likely duplicate of #368

**Comment by russcam** [comment] 2020-05-20 00:17
Closing this as duplicate of #363. Please see workaround: https://github.com/elastic/windows-installers/issues/363#issuecomment-631158455

**Closed by russcam** 2020-05-20 00:17 UTC
Labels: v7.7.0
