### ISSUE TITLE
Install elasticsearch 7.7 on windows server 2012 will fail

### ISSUE THREAD

**Issue by david-at-fiziico** [elastic/windows-installers#370] opened 2020-05-20 13:15 UTC
### Environment

no proxy server
[MSIeb8ce.LOG](https://github.com/elastic/windows-installers/files/4657041/MSIeb8ce.LOG)

Taiwan

### Steps to reproduce the behaviour
Install on windows server 2012 with default option will just fail.
Windows server 2012 is running on a VM.

1.Fresh install
2.
3.

![image](https://user-images.githubusercontent.com/10862584/82449893-c8863d00-9a60-11ea-8862-ead52fca15c1.png)

**Comment by ygel** [comment] 2020-05-20 13:30
Hello @david-at-fiziico, this is most likely a duplicate of https://github.com/elastic/windows-installers/issues/363

**Comment by david-at-fiziico** [comment] 2020-05-21 03:06
@ygel Thanks, just tried #363 , it works.

**Comment by russcam** [comment] 2020-05-21 04:54
From https://github.com/elastic/windows-installers/issues/363#issuecomment-631868145

> Logs is pasted here, what's the minimum requirement of RAM?
> 
> Java HotSpot(TM) 64-Bit Server VM (25.212-b10) for windows-amd64 JRE (1.8.0_212-b10), built on Apr 1 2019 22:50:23 by "java_re" with MS VC++ 10.0 (VS2010)
> Memory: 4k page, physical 2096696k(1023132k free), swap 3033920k(1456520k free)
> CommandLine flags: -XX:CMSInitiatingOccupancyFraction=75 -XX:ErrorFile=logs/hs_err_pid%p.log -XX:GCLogFileSize=67108864 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:InitialHeapSize=536870912 -XX:MaxHeapSize=536870912 -XX:MaxNewSize=87244800 -XX:MaxTenuringThreshold=6 -XX:NewSize=87244800 -XX:NumberOfGCLogFiles=32 -XX:OldPLABSize=16 -XX:OldSize=174489600 -XX:+PrintFlagsFinal -XX:+PrintGC -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:-RequireSharedSpaces -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseGCLogFileRotation -XX:-UseLargePagesIndividualAllocation -XX:+UseParNewGC -XX:-UseSharedSpaces
> Heap
> par new generation total 76672K, used 2726K [0x00000000e0000000, 0x00000000e5330000, 0x00000000e5330000)
> eden space 68160K, 4% used [0x00000000e0000000, 0x00000000e02a9b18, 0x00000000e4290000)
> from space 8512K, 0% used [0x00000000e4290000, 0x00000000e4290000, 0x00000000e4ae0000)
> to space 8512K, 0% used [0x00000000e4ae0000, 0x00000000e4ae0000, 0x00000000e5330000)
> concurrent mark-sweep generation total 439104K, used 0K [0x00000000e5330000, 0x0000000100000000, 0x0000000100000000)
> Metaspace used 2246K, capacity 4480K, committed 4480K, reserved 1056768K
> class space used 246K, capacity 384K, committed 384K, reserved 1048576K

**Comment by russcam** [comment] 2020-05-21 07:16
> Logs is pasted here, what's the minimum requirement of RAM?

@david-at-fiziico I think we run integration tests with 512Mb heap size, but on machines with 32Gb RAM (which will be used by filesystem cache).

**Comment by ygel** [comment] 2020-07-14 02:55
Closing as stale, please reopen if problem persists

**Closed by ygel** 2020-07-14 02:55 UTC
Labels: awaiting response, v7.7.0
