### ISSUE TITLE
This is very unfortunate and not something we'd hope to repeat.  Please let us know by filing an issue on our GitHub issues page.

### ISSUE THREAD

**Issue by MaqSaid** [elastic/windows-installers#64] opened 2017-08-01 02:08 UTC

**Comment by russcam** [comment] 2017-08-01 03:50
Was there an error in installation @MaqSaid? Do you have the installation log?

**Comment by parsasaei** [comment] 2017-08-01 04:58
I have the same issue.

**Comment by russcam** [comment] 2017-08-01 05:12
@parsasaei would you be able to provide the [msi installation log](https://github.com/elastic/windows-installers#reporting-problems)?

**Comment by parsasaei** [comment] 2017-08-01 05:24
```
=== Logging started: 8/1/2017  9:51:52 ===
Action start 9:51:52: INSTALL.
Action start 9:51:52: FindRelatedProducts.
Action ended 9:51:52: FindRelatedProducts. Return value 1.
Action start 9:51:52: AppSearch.
Action ended 9:51:52: AppSearch. Return value 1.
Action start 9:51:52: LaunchConditions.
Action ended 9:51:52: LaunchConditions. Return value 1.
Action start 9:51:52: ValidateProductID.
Action ended 9:51:52: ValidateProductID. Return value 1.
Action start 9:51:52: CostInitialize.
Action ended 9:51:52: CostInitialize. Return value 1.
Action start 9:51:52: FileCost.
Action ended 9:51:52: FileCost. Return value 1.
Action start 9:51:52: CostFinalize.
Action ended 9:51:52: CostFinalize. Return value 1.
Action start 9:51:52: InstallValidate.
Action ended 9:51:52: InstallValidate. Return value 1.
Action start 9:51:52: RemoveExistingProducts.
Action ended 9:51:52: RemoveExistingProducts. Return value 1.
Action start 9:51:52: InstallInitialize.
Action ended 9:51:52: InstallInitialize. Return value 1.
Action start 9:51:52: Action1SetProp_DATADIRECTORY.
Action ended 9:51:52: Action1SetProp_DATADIRECTORY. Return value 1.
Action start 9:51:52: Action2SetProp_CONFIGDIRECTORY.
Action ended 9:51:52: Action2SetProp_CONFIGDIRECTORY. Return value 1.
Action start 9:51:52: Action3SetProp_LOGSDIRECTORY.
Action ended 9:51:52: Action3SetProp_LOGSDIRECTORY. Return value 1.
Action start 9:51:52: Action4SetProp_NODENAME.
Action ended 9:51:52: Action4SetProp_NODENAME. Return value 1.
Action start 9:51:52: ElasticsearchServiceStopAction.
Action ended 9:51:52: ElasticsearchServiceStopAction. Return value 1.
Action start 9:51:52: ElasticsearchValidateArgumentsAction.
SFXCA: Extracting custom action to temporary directory: C:\Users\parsa\AppData\Local\Temp\MSI28B8.tmp-\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.ElasticsearchValidateArgumentsAction.ElasticsearchValidateArguments
Passed Args:
PLACEWRITABLELOCATIONSINSAMEPATH=, INSTALLDIR=C:\Program Files\Elastic\Elasticsearch\, DATADIRECTORY=C:\ProgramData\Elastic\Elasticsearch\data, CONFIGDIRECTORY=C:\ProgramData\Elastic\Elasticsearch\config, LOGSDIRECTORY=C:\ProgramData\Elastic\Elasticsearch\logs, UNICASTNODES=, CLUSTERNAME=elasticsearch, NODENAME=DESKTOP-F4CELNU, MASTERNODE=true, DATANODE=true, INGESTNODE=true, SELECTEDMEMORY=, LOCKMEMORY=false, MINIMUMMASTERNODES=, NETWORKHOST=, HTTPPORT=9200, TRANSPORTPORT=9300, INSTALLASSERVICE=true, STARTAFTERINSTALL=true, STARTWHENWINDOWSSTARTS=true, USELOCALSYSTEM=true, USEEXISTINGUSER=, USENETWORKSERVICE=false, USER=, PASSWORD=, PLUGINS=, OPENDOCUMENTATIONAFTERINSTALLATION=
ViewModelState:
ElasticsearchInstallationModel
- IsValid = True
- ValidationFailures = 
- MsiLogFileLocation = C:\Users\parsa\Desktop\install.log
- JavaInstalled = True
- JavaMisconfigured = False
- Using32BitJava = False
- BadElasticsearchYamlFile = False
NoticeModel
- IsValid = True

LocationsModel
- IsValid = True
- ConfigureAllLocations = True
- PlaceWritableLocationsInSamePath = False
- ConfigureLocations = True
- InstallDir = C:\Program Files\Elastic\Elasticsearch\
- DataDirectory = C:\ProgramData\Elastic\Elasticsearch\data
- ConfigDirectory = C:\ProgramData\Elastic\Elasticsearch\config
- LogsDirectory = C:\ProgramData\Elastic\Elasticsearch\logs

ServiceModel
- IsValid = True
- InstallAsService = True
- StartAfterInstall = True
- StartWhenWindowsStarts = True
- UseLocalSystem = True
- UseExistingUser = False
- UseNetworkService = False
- User = 
- Password = False

ConfigurationModel
- IsValid = True
- UnicastNodes = 
- ClusterName = elasticsearch
- NodeName = DESKTOP-F4CELNU
- MasterNode = True
- DataNode = True
- IngestNode = True
- TotalPhysicalMemory = 4055
- SelectedMemory = 2027
- MinimumMasterNodes = 0
- LockMemory = False
- NetworkHost = 
- HttpPort = 9200
- TransportPort = 9300

PluginsModel
- IsValid = True
- Plugins = 


Action ended 9:51:53: ElasticsearchValidateArgumentsAction. Return value 1.
Action start 9:51:54: Set_ElasticsearchConfigurationAction_Props.
Action ended 9:51:54: Set_ElasticsearchConfigurationAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchDirectoriesAction_Props.
Action ended 9:51:54: Set_ElasticsearchDirectoriesAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchEnvironmentAction_Props.
Action ended 9:51:54: Set_ElasticsearchEnvironmentAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchJvmOptionsAction_Props.
Action ended 9:51:54: Set_ElasticsearchJvmOptionsAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchPluginsAction_Props.
Action ended 9:51:54: Set_ElasticsearchPluginsAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchRollbackDirectoriesAction_Props.
Action ended 9:51:54: Set_ElasticsearchRollbackDirectoriesAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchRollbackEnvironmentAction_Props.
Action ended 9:51:54: Set_ElasticsearchRollbackEnvironmentAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchRollbackServiceAction_Props.
Action ended 9:51:54: Set_ElasticsearchRollbackServiceAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchServiceInstallAction_Props.
Action ended 9:51:54: Set_ElasticsearchServiceInstallAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchServiceStartAction_Props.
Action ended 9:51:54: Set_ElasticsearchServiceStartAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchServiceStopAction_Props.
Action ended 9:51:54: Set_ElasticsearchServiceStopAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchUninstallDirectoriesAction_Props.
Action ended 9:51:54: Set_ElasticsearchUninstallDirectoriesAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchUninstallEnvironmentAction_Props.
Action ended 9:51:54: Set_ElasticsearchUninstallEnvironmentAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchUninstallPluginsAction_Props.
Action ended 9:51:54: Set_ElasticsearchUninstallPluginsAction_Props. Return value 1.
Action start 9:51:54: Set_ElasticsearchUninstallServiceAction_Props.
Action ended 9:51:54: Set_ElasticsearchUninstallServiceAction_Props. Return value 1.
Action start 9:51:54: ProcessComponents.
Action ended 9:51:54: ProcessComponents. Return value 1.
Action start 9:51:54: UnpublishFeatures.
Action ended 9:51:54: UnpublishFeatures. Return value 1.
Action start 9:51:54: RemoveFiles.
Action ended 9:51:54: RemoveFiles. Return value 1.
Action start 9:51:54: InstallFiles.
Action ended 9:51:54: InstallFiles. Return value 1.
Action start 9:51:54: RegisterUser.
Action ended 9:51:54: RegisterUser. Return value 1.
Action start 9:51:54: RegisterProduct.
Action ended 9:51:54: RegisterProduct. Return value 1.
Action start 9:51:54: PublishFeatures.
Action ended 9:51:54: PublishFeatures. Return value 1.
Action start 9:51:54: PublishProduct.
Action ended 9:51:54: PublishProduct. Return value 1.
Action start 9:51:54: ElasticsearchRollbackEnvironmentAction.
Action ended 9:51:54: ElasticsearchRollbackEnvironmentAction. Return value 1.
Action start 9:51:54: ElasticsearchEnvironmentAction.
Action ended 9:51:54: ElasticsearchEnvironmentAction. Return value 1.
Action start 9:51:54: ElasticsearchRollbackDirectoriesAction.
Action ended 9:51:54: ElasticsearchRollbackDirectoriesAction. Return value 1.
Action start 9:51:54: ElasticsearchDirectoriesAction.
Action ended 9:51:54: ElasticsearchDirectoriesAction. Return value 1.
Action start 9:51:54: ElasticsearchConfigurationAction.
Action ended 9:51:54: ElasticsearchConfigurationAction. Return value 1.
Action start 9:51:54: ElasticsearchJvmOptionsAction.
Action ended 9:51:54: ElasticsearchJvmOptionsAction. Return value 1.
Action start 9:51:54: ElasticsearchPluginsAction.
Action ended 9:51:54: ElasticsearchPluginsAction. Return value 1.
Action start 9:51:54: ElasticsearchRollbackServiceAction.
Action ended 9:51:54: ElasticsearchRollbackServiceAction. Return value 1.
Action start 9:51:54: ElasticsearchServiceInstallAction.
Action ended 9:51:54: ElasticsearchServiceInstallAction. Return value 1.
Action start 9:51:54: ElasticsearchServiceStartAction.
Action ended 9:51:54: ElasticsearchServiceStartAction. Return value 1.
Action start 9:51:54: InstallFinalize.
MSI (s) (24:C8) [09:51:54:237]: Product: Elasticsearch 5.5.1 -- Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as administrator and then retry this installation.

Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as administrator and then retry this installation.
Action ended 9:51:54: InstallFinalize. Return value 3.
Action ended 9:51:54: INSTALL. Return value 3.
MSI (s) (24:C8) [09:51:54:299]: Product: Elasticsearch 5.5.1 -- Installation failed.

MSI (s) (24:C8) [09:51:54:299]: Windows Installer installed the product. Product Name: Elasticsearch 5.5.1. Product Version: 5.5.1. Product Language: 1033. Manufacturer: Elastic. Installation success or error status: 1603.

=== Logging stopped: 8/1/2017  9:51:54 ===

```
@russcam Is this that?

**Comment by YuryZh** [comment] 2017-08-01 22:21
Hi, I have the same problem. Log is attached.
[MSIb071f.LOG.txt](https://github.com/elastic/windows-installers/files/1192110/MSIb071f.LOG.txt)

**Comment by russcam** [comment] 2017-08-02 00:42
@parsasaei The error log indicates that you do not have sufficient privileges to install for all the users on the machine

> Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as administrator and then retry this installation.

Currently, you must be an administrator on the machine to perform the installation or an administrator can make changes to allow non-administrators to install the MSI.

**Comment by russcam** [comment] 2017-08-02 00:51
@YuryZh The installation failed for a different reason for you. Elasticsearch was set to be installed as a service, but the installation process never saw the service start successfully

> ....
> [0] waiting to start waiting to start
> [0] waiting to start waiting to start
> System.ServiceProcess.TimeoutException: Timeout has expired and the operation has not been completed in 00:01:00.
>    в Elastic.Installer.Domain.Configuration.Service.ServiceStateProvider.StartAndWaitForRunning(TimeSpan timeToWait, Int32 totalTicks)
>    в Elastic.InstallerHosts.Elasticsearch.Tasks.StartServiceTask.ExecuteTask()
>    в Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
> CustomAction ElasticsearchServiceStartAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> Action ended 8:05:51: InstallFinalize. Return value 3.

There could be a number of different reasons why this has happened

1. An exception thrown when Elasticsearch starts which causes the service to not respond as started
2. An intermittent service start issue

For 1, I think it would be good for the installer to see if an Elasticsearch log file has been written and if so, write the contents to the MSI log in the event the service has not started successfully. This will provide us more information in determining root cause.

To rule out 2, would you be able to try the installation again, or try to install without installing as a service and [manually starting the elasticsearch.exe process](https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html#msi-installer-command-line-running), to see if it starts successfully?

**Comment by russcam** [comment] 2017-08-02 01:57
Actually, the installer does already dump the Elasticsearch log to the MSI log in the event of a rollback, if it exists.

@YuryZh looks like there was also an issue in deleting the data directory at `C:\ProgramData\Elastic\Elasticsearch\data`. Can you delete all of `C:\ProgramData\Elastic` and try again?

**Comment by parsasaei** [comment] 2017-08-02 05:21
@russcam still having problem.please see my msi installation log: 
[MSId4a48.txt](https://github.com/elastic/windows-installers/files/1192717/MSId4a48.txt)

**Comment by russcam** [comment] 2017-08-02 06:42
@parsasaei The log indicates that there is an issue installing X-Pack

> -> Downloading x-pack from elastic
> Exception in thread "main" java.io.IOException: Server returned HTTP response code: 451 for URL: https://artifacts.elastic.co/downloads/elasticsearch-plugins/x-pack/x-pack-5.5.1.zip
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
> 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889)
> 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
> 	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:326)
> 	at org.elasticsearch.plugins.InstallPluginCommand.downloadZipAndChecksum(InstallPluginCommand.java:371)
> 	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:225)
> 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
> 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
> 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
> 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
> 	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
> 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
> 	at org.elasticsearch.cli.Command.main(Command.java:88)
> 	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

The plugin is downloaded from an S3 bucket and [according to the error responses for S3](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList), Response code 451 is not listed. What I think is likely is that there is a corporate proxy blocking the download, similar to https://github.com/elastic/windows-installers/issues/61

**Comment by YuryZh** [comment] 2017-08-02 14:02
@russcam 
Hi. I deleted C:\ProgramData\Elastic folder. And tried again to install the Elasticsearch, but unsuccessfully, Log is attached. 
[MSI29c2f (installation log).txt](https://github.com/elastic/windows-installers/files/1194117/MSI29c2f.installation.log.txt)

Second, installation with manual start of the Elasticsearch is work! 
Thanks!

**Comment by russcam** [comment] 2017-09-25 06:54
@YuryZh The latest log looks again like the Windows Service did not start successfully. Since you've been able to successfully install and manually start the process, I'm going to close this issue. Thanks again for reporting.

@parsasaei HTTP status code 451 means that the resource cannot be downloaded in your current location as it is unavailable for legal reasons.

**Closed by russcam** 2017-09-25 06:54 UTC

**Comment by athiappang** [comment] 2018-04-16 05:27
I am also getting the same error message.
PFA the log file. Please 
[MSI24e0d.LOG](https://github.com/elastic/windows-installers/files/1913952/MSI24e0d.LOG)
help me in this regards.

**Comment by russcam** [comment] 2018-04-16 05:43
@athiappang Could you please try to install **without starting the service as part of the installation**, then once installation completes successfully, start the service afterwards. Please report back here how that goes.

**Comment by vaibhav8600** [comment] 2019-04-05 05:14
I HAVE FACING SAME ISSUE PLEASE [HELP](url) E WITH THAT

[MSI941e1.LOG](https://github.com/elastic/windows-installers/files/3046429/MSI941e1.LOG)
