### ISSUE TITLE
An error occured during installation - ES7.7.1 - WS2019

### ISSUE THREAD

**Issue by cedricnuyts** [elastic/windows-installers#377] opened 2020-06-09 09:43 UTC
At the end of the installation, the UI is showing "An error occured during installation!".

- Installation was done on a Windows Server 2019 Standard with the MSI-installer.
- Version tried to install is 7.7.1

Installation directory = C:\Program Files\Elastic\Elasticsearch\7.7.1
Configuration directory = D:\Elastic\Elasticsearch\config
Data directory = D:\Elastic\Elasticsearch\data
Logs directory = D:\Elastic\Elasticsearch\logs

[log.txt](https://github.com/elastic/windows-installers/files/4751242/log.txt)

**Comment by reighnman** [comment] 2020-06-09 18:34
Duplicate of #371

**Comment by ygel** [comment] 2020-07-14 02:45
closing with https://github.com/elastic/windows-installers/pull/379

**Closed by ygel** 2020-07-14 02:45 UTC
Labels: v7.7.1
