### ISSUE TITLE
Error occured during installation 

### ISSUE THREAD

**Issue by duddukurimd** [elastic/windows-installers#174] opened 2018-04-04 17:37 UTC
### Steps to reproduce the behaviour

1.Fresh installation
2. Installation in not getting completed and get to find the below log details from the log file
Error : 
[2018-04-04T23:02:22,813][INFO ][o.e.l.LicenseService     ] [elk] license [9bc3f2f8-063d-4d73-ab2e-6141db6518c5] mode [basic] - valid
[2018-04-04T23:02:22,927][INFO ][o.e.g.GatewayService     ] [elk] recovered [1] indices into cluster_state
[2018-04-04T23:02:23,477][INFO ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [elk] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2018-04-04T23:02:23,477][INFO ][o.e.n.Node               ] [elk] started
[2018-04-04T23:02:24,157][INFO ][o.e.c.r.a.AllocationService] [elk] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[.monitoring-es-6-2018.04.04][0]] ...]).
[2018-04-04T23:02:27,113][INFO ][o.e.n.Node               ] [elk] stopping ...
[2018-04-04T23:02:27,129][INFO ][o.e.x.w.WatcherService   ] [elk] stopping watch service, reason [shutdown initiated]
[2018-04-04T23:02:27,130][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [controller/14760] [Main.cc@168] Ml controller exiting
[2018-04-04T23:02:27,130][INFO ][o.e.x.m.j.p.NativeController] Native controller process has stopped - no new native processes can be started
[2018-04-04T23:02:27,672][INFO ][o.e.n.Node               ] [elk] stopped
[2018-04-04T23:02:27,672][INFO ][o.e.n.Node               ] [elk] closing ...
[2018-04-04T23:02:27,682][INFO ][o.e.n.Node               ] [elk] closed

<img width="682" alt="installation error" src="https://user-images.githubusercontent.com/22025315/38324090-caed6e9c-382e-11e8-9581-6c5d22b4fdce.PNG">

**Comment by Mpdreamz** [comment] 2018-04-19 12:13
Closing as could not reproduce, feel free to reopen with the MSI log.

**Closed by Mpdreamz** 2018-04-19 12:13 UTC
