### ISSUE TITLE
MSI installation on Windows 10 enterprise

### ISSUE THREAD

**Issue by surapaneniSri** [elastic/windows-installers#294] opened 2019-05-01 22:39 UTC
### Environment

 YES
 USA

### Expected Behaviour
Expected to install without any issues.
### Actual Behaviour
![image](https://user-images.githubusercontent.com/27215934/57048040-8ebd7b00-6c40-11e9-837a-c8e58932dcb0.png)

### Steps to reproduce the behaviour

 Fresh install - Trial

1.
2.
[MSI973fd.LOG](https://github.com/elastic/windows-installers/files/3136224/MSI973fd.LOG)

3.

**Comment by ygel** [comment] 2019-07-10 16:45
Duplicate of #305

**Closed by ygel** 2019-07-10 16:45 UTC
