### ISSUE TITLE
MSI install on Windows 2016 Server failed

### ISSUE THREAD

**Issue by AZbman** [elastic/windows-installers#297] opened 2019-05-02 22:11 UTC
[MSI7d5fb.LOG](https://github.com/elastic/windows-installers/files/3140126/MSI7d5fb.LOG)

### Environment
I am not running behind a corporate proxy. The system is located on a home office / lab network. Connecting to the internet via Cox Communications Gigabit internet service.  The operating systems is a clean install of Windows Server 2016 Standard. Installed on a bare metal physical system (Pentium dual core E5500 @ 2.80 GHz, with 4GB memory).

### Expected Behaviour
a functional installation of elasticsearch
### Actual Behaviour
MSI install fails
### Steps to reproduce the behaviour
1. this is a fresh install from elasticsearch-7.0.1.msi, which was downloaded 05/02/2019

**Comment by ygel** [comment] 2019-07-10 16:36
Duplicate of #305

**Closed by ygel** 2019-07-10 16:36 UTC
