### ISSUE TITLE
Unable to install 7.7.0

### ISSUE THREAD

**Issue by JHeLiu** [elastic/windows-installers#366] opened 2020-05-15 02:11 UTC
Unable to install 7.7.0 

No matter whether the installation package or compressed package is used, the service cannot be started in the end. On winserver 2016, 7.6.2 everything works

java sdk 12.x or 14.x tried, all are invalid

logs....↓↓↓↓↓
[log.txt](https://github.com/elastic/windows-installers/files/4631897/log.txt)
logs....↑↑↑↑↑

**Comment by Jujubz** [comment] 2020-05-17 12:21
I'm having the same issue, 7.7.0 on win 10. SDK 14.0.1 Java 8u251.
[ElasticsearchLOG.txt](https://github.com/elastic/windows-installers/files/4640215/ElasticsearchLOG.txt)

**Comment by Smahdie** [comment] 2020-05-19 06:00
Same issue here on windows server 2016. I tried installing .zip and .msi packages of ElasticSearch 7.7.0 , also tried it with jdk-11.0.7 and jdk-14.0.1, still no luck. I also have reported the issue in [discussion.elastic.co](https://discuss.elastic.co/t/cant-install-elastic-as-a-windows-service/233131)

Here's my last installation log:
[installationLog.txt](https://github.com/elastic/windows-installers/files/4648481/installationLog.txt)

**Comment by reighnman** [comment] 2020-05-19 14:20
Likely duplicate of #368

**Comment by russcam** [comment] 2020-05-20 00:18
Closing this as duplicate of #363. Please see workaround: https://github.com/elastic/windows-installers/issues/363#issuecomment-631158455

**Closed by russcam** 2020-05-20 00:18 UTC
Labels: v7.7.0
