### ISSUE TITLE
MSI Installation on Windows 8 - error occured

### ISSUE THREAD

**Issue by kzevolis** [elastic/windows-installers#293] opened 2019-04-30 16:54 UTC
Hi,

i encountered an error during installation of MSI 7.0.0 on Windows 8 pc.
Find attached the related logs.

Looking forward to your response.
[MSIc7235.LOG](https://github.com/elastic/windows-installers/files/3132247/MSIc7235.LOG)

**Comment by dnscorp** [comment] 2019-05-01 03:26
Error occurred when tried on windows 10. Used MSI 7.0

[MSI72066.LOG](https://github.com/elastic/windows-installers/files/3133752/MSI72066.LOG)

**Comment by ygel** [comment] 2019-07-10 16:48
@kzevolis Looks like a duplicate of #305 


@dnscorp Please try v7.2.0, there might have been a problem with ingest plugin in v7.0

```
-> Installed ingest-attachment
[0] installing ingest-attachment installing ingest-attachment
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\7.0.0\bin\elasticsearch-plugin.bat install ingest-attachment --batch). ExitCode: 0 ErrorCheck: True ErrorOut:WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/C:/Program%20Files/Elastic/Elasticsearch/7.0.0/lib/tools/plugin-cli/bcprov-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

   at Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.Installer.Domain.Configuration.Plugin.ElasticsearchPluginStateProvider.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments, IDictionary`2 environmentVariables)
   at Elastic.InstallerHosts.Elasticsearch.Tasks.Install.InstallPluginsTask.ExecuteTask()
   at Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)```

**Closed by ygel** 2019-07-10 16:48 UTC
