### ISSUE TITLE
Error occured during MSI installation (7.0)

### ISSUE THREAD

**Issue by alyacom** [elastic/windows-installers#292] opened 2019-04-25 08:29 UTC
error during installation
OS : Windows server 2012
[MSIf59a3.LOG](https://github.com/elastic/windows-installers/files/3115940/MSIf59a3.LOG)

**Comment by ygel** [comment] 2019-07-10 16:53
Likely duplicate of #311 

```
[0] installing ingest-attachment installing ingest-attachment
-> Downloading ingest-attachment from elastic
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessClassInPackage.sun.java2d.cmm.kcms
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed ingest-attachment
[0] installing ingest-attachment installing ingest-attachment
[0] installed ingest-attachment installed ingest-attachment
[0] installing ingest-geoip installing ingest-geoip
A tool for managing installed elasticsearch plugins
Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - removes a plugin from Elasticsearch
Non-option arguments:
command              
Option         Description        
------         -----------        
-h, --help     show help          
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: Unknown plugin ingest-geoip
[0] installing ingest-geoip installing ingest-geoip
```

**Closed by ygel** 2019-07-10 16:53 UTC
