### ISSUE TITLE
Fresh installation failed for elasticsearch-7.7.0.msi

### ISSUE THREAD

**Issue by shivadixit11** [elastic/windows-installers#364] opened 2020-05-14 09:11 UTC
Fresh Installtion failed for elasticsearch-7.7.0.msi

### Environment
Windows 10 (localhost)

![image](https://user-images.githubusercontent.com/17043099/81915929-d36c4800-95f0-11ea-803a-4742d9e3a24d.png)
[installations_logs.LOG](https://github.com/elastic/windows-installers/files/4627205/installations_logs.LOG)

**Comment by russcam** [comment] 2020-05-20 00:18
Closing this as duplicate of #363. Please see workaround: https://github.com/elastic/windows-installers/issues/363#issuecomment-631158455

**Closed by russcam** 2020-05-20 00:18 UTC
Labels: v7.7.0
