### ISSUE TITLE
Instillation Failure Can you help? 

### ISSUE THREAD

**Issue by thecodex101** [elastic/windows-installers#58] opened 2017-07-13 13:02 UTC
Please can you help me identify the issue. 

Cheers

Ian 

[MSI5a1de.txt](https://github.com/elastic/windows-installers/files/1145204/MSI5a1de.txt)

**Comment by eskibars** [comment] 2017-07-28 01:05
This looks like it's because you've chosen to install some plugins but you're not online (or you have a corporate proxy that's getting in the way of a direct connection).

I'm going to close this as a duplicate of https://github.com/elastic/windows-installers/issues/61

**Closed by eskibars** 2017-07-28 01:05 UTC
